// <auto-generated />
using System;
using BasisEntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasisEntityFramework.Migrations
{
    [DbContext(typeof(AnimeContext))]
    [Migration("20231119210840_InitialCreateDB")]
    partial class InitialCreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasisEntityFramework.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlStaffel")
                        .HasColumnType("int");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductionStudio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Folge", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("Daeur")
                        .HasColumnType("datetime2");

                    b.Property<int>("FolgeNummer")
                        .HasColumnType("int");

                    b.Property<string>("FolgeTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffelId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("StaffelId");

                    b.ToTable("Folges");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Staffel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnimeId")
                        .HasColumnType("int");

                    b.Property<int>("AnzahlFolge")
                        .HasColumnType("int");

                    b.Property<string>("StafellName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StafellNummer")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Staffels");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Folge", b =>
                {
                    b.HasOne("BasisEntityFramework.Models.Staffel", null)
                        .WithMany("Folges")
                        .HasForeignKey("StaffelId");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Staffel", b =>
                {
                    b.HasOne("BasisEntityFramework.Models.Anime", null)
                        .WithMany("Staffels")
                        .HasForeignKey("AnimeId");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Anime", b =>
                {
                    b.Navigation("Staffels");
                });

            modelBuilder.Entity("BasisEntityFramework.Models.Staffel", b =>
                {
                    b.Navigation("Folges");
                });
#pragma warning restore 612, 618
        }
    }
}
